export default class AgencyActionTypes
{
static LOGINACTION:String="LOGIN";
static SIGNUPACTION:String="SIGNUP";
static CHECKUSERACTION:String="CHECKUSER";
static GETARTICLES:String="GETARTICLE";
static SAVEARTICLES:String="SAVEARTICLE"
static GETUSERARTICLES:String="USERARTICLES";
static DELETEARTICLE:String="DELETEARTICLE";
}